# Generated by Django 6.0 on 2025-12-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0002_insulintype_alter_insulindose_insulin_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="insulintype",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
