# Generated by Django 6.0 on 2025-12-22 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0003_insulintype_is_default"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="glucosereading",
            name="entries_glu_user_id_4ffb13_idx",
        ),
        migrations.RemoveIndex(
            model_name="insulindose",
            name="entries_ins_user_id_d7b65b_idx",
        ),
        migrations.RemoveIndex(
            model_name="meal",
            name="entries_mea_user_id_5865c9_idx",
        ),
        migrations.RenameField(
            model_name="glucosereading",
            old_name="user",
            new_name="last_modified_by",
        ),
        migrations.RenameField(
            model_name="insulindose",
            old_name="user",
            new_name="last_modified_by",
        ),
        migrations.RenameField(
            model_name="meal",
            old_name="user",
            new_name="last_modified_by",
        ),
        migrations.AddField(
            model_name="insulintype",
            name="last_modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_insulin_types",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="glucosereading",
            index=models.Index(
                fields=["last_modified_by", "-occurred_at"],
                name="entries_glu_last_mo_2d7ef3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="insulindose",
            index=models.Index(
                fields=["last_modified_by", "-occurred_at"],
                name="entries_ins_last_mo_882eaa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(
                fields=["last_modified_by", "-occurred_at"],
                name="entries_mea_last_mo_96efa0_idx",
            ),
        ),
    ]
