# Generated by Django 6.0 on 2025-12-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "entries",
            "0004_remove_glucosereading_entries_glu_user_id_4ffb13_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="insulindose",
            name="brand_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="insulindose",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
