# Generated by Django 6.0 on 2025-12-22 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0005_alter_insulindose_brand_name_alter_insulindose_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="insulindose",
            name="brand_name",
        ),
    ]
