# Generated by Django 6.0 on 2025-12-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0006_remove_insulindose_brand_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="insulintype",
            name="type",
            field=models.CharField(
                choices=[
                    ("rapid", "Rapid-Acting"),
                    ("short", "Short-Acting"),
                    ("intermediate", "Intermediate-Acting"),
                    ("long", "Long-Acting"),
                    ("ultra_long", "Ultra Long-Acting"),
                    ("premixed", "Premixed"),
                ],
                default="rapid",
                max_length=20,
            ),
        ),
    ]
