# Generated by Django 6.0 on 2025-12-22 13:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0007_insulintype_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsulinSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(
                        help_text="Label for this scheduled dose", max_length=100
                    ),
                ),
                ("time", models.TimeField(help_text="Scheduled time for this dose")),
                (
                    "units",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Scheduled units of insulin",
                        max_digits=5,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "insulin_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="entries.insulintype",
                    ),
                ),
            ],
            options={
                "ordering": ["time"],
            },
        ),
    ]
