# Generated by Django 6.0 on 2025-12-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0008_insulinschedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insulinschedule",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
