# Generated by Django 6.0 on 2025-12-22 13:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0009_alter_insulinschedule_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorrectionScale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "greater_than",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Blood glucose threshold (e.g., 8.0 mmol/L)",
                        max_digits=5,
                    ),
                ),
                (
                    "units_to_add",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Units of insulin to add when above threshold",
                        max_digits=5,
                    ),
                ),
            ],
            options={
                "ordering": ["greater_than"],
            },
        ),
    ]
