# Generated by Django 6.0 on 2025-12-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0010_correctionscale"),
    ]

    operations = [
        migrations.RenameField(
            model_name="insulindose",
            old_name="units",
            new_name="base_units",
        ),
        migrations.AddField(
            model_name="insulindose",
            name="correction_units",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
